#!/usr/bin/env python3
"""Generate ECDSA-P256 test vectors for tests/lib/crypto/.

Creates a deterministic set of NIST P-256 (secp256r1) signatures using
Python's cryptography library, then prints a C header containing two
valid (P) vectors and two tampered (F) vectors. The tampered vectors
flip a single byte in either the message hash or the signature to
trigger a verify failure.

We do not embed the NIST CAVP SigVer.rsp vectors verbatim because
their authenticity is hard to assert without re-downloading the ZIP.
Instead we generate-then-verify locally with cryptography (a known-good
implementation), then ship the bytes — micro-ecc must agree.
"""
import hashlib
from cryptography.hazmat.primitives.asymmetric import ec, utils as asym_utils
from cryptography.hazmat.primitives import serialization, hashes
from cryptography.hazmat.primitives.asymmetric.utils import (
    decode_dss_signature, encode_dss_signature,
)
from cryptography.exceptions import InvalidSignature

CURVE = ec.SECP256R1()


def fixed_bytes(seed: bytes) -> ec.EllipticCurvePrivateKey:
    """Derive a deterministic key from `seed` using HKDF-SHA256."""
    h = hashlib.sha256(seed).digest()
    # Treat as a private scalar (mod n). cryptography accepts an int in
    # range [1, n-1].
    n = 0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551
    val = int.from_bytes(h, "big") % (n - 1) + 1
    return ec.derive_private_key(val, CURVE)


def sign(key, msg: bytes) -> tuple[bytes, bytes, bytes]:
    """Return (msg_hash, sig_r_s_64, ecdsa_signature_bytes)."""
    sig_der = key.sign(msg, ec.ECDSA(hashes.SHA256()))
    r, s = decode_dss_signature(sig_der)
    rs = r.to_bytes(32, "big") + s.to_bytes(32, "big")
    msg_hash = hashlib.sha256(msg).digest()
    return msg_hash, rs, sig_der


def pubkey_xy(key) -> bytes:
    """Return uncompressed 64-byte X || Y."""
    pub = key.public_key().public_numbers()
    return pub.x.to_bytes(32, "big") + pub.y.to_bytes(32, "big")


def verify_locally(key, msg_hash: bytes, rs: bytes) -> bool:
    r = int.from_bytes(rs[:32], "big")
    s = int.from_bytes(rs[32:], "big")
    try:
        key.public_key().verify(
            encode_dss_signature(r, s),
            msg_hash,
            ec.ECDSA(asym_utils.Prehashed(hashes.SHA256())),
        )
        return True
    except InvalidSignature:
        return False


def emit_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 8):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


VECTORS = [
    # (label, seed, message, expected_pass, tamper)
    ("v1", b"stm32-bare-metal/v1", b"hello world", True, None),
    ("v2", b"stm32-bare-metal/v2", b"firmware image v0.1.0", True, None),
    ("v3", b"stm32-bare-metal/v3", b"tampered hash", False, "hash"),
    ("v4", b"stm32-bare-metal/v4", b"tampered signature", False, "sig"),
]

print('/*')
print(' * ECDSA-P256 (secp256r1) test vectors.')
print(' *')
print(' * NIST FIPS 186-4 §6.4 specifies the verify procedure that we drive.')
print(' * These four vectors are deterministically generated by')
print(' * tests/lib/crypto/vectors/gen_vectors.py using the Python')
print(' * `cryptography` library (which itself uses OpenSSL). They are NOT')
print(' * the NIST CAVS SigVer.rsp vectors verbatim, but they exercise the')
print(' * same verify path: two valid signatures (Result = P) and two')
print(' * tampered cases (Result = F) — one with a flipped hash byte, one')
print(' * with a flipped signature byte. Each was cross-verified with')
print(' * cryptography before being committed.')
print(' *')
print(' * Each vector provides:')
print(' *   pubkey[64]  = Qx || Qy')
print(' *   hash[32]    = SHA-256(msg) (post-tampering for v3)')
print(' *   sig[64]     = R || S (post-tampering for v4)')
print(' *   expect      = expected return value of crypto_ecdsa_p256_verify')
print(' */')
print('#ifndef LIB_CRYPTO_FIPS_186_4_P256_H')
print('#define LIB_CRYPTO_FIPS_186_4_P256_H')
print('')
print('#include <stdint.h>')
print('')

for label, seed, msg, expect, tamper in VECTORS:
    key = fixed_bytes(seed)
    msg_hash, rs, _ = sign(key, msg)
    assert verify_locally(key, msg_hash, rs), f"clean verify failed for {label}"
    if tamper == "hash":
        msg_hash = bytearray(msg_hash)
        msg_hash[0] ^= 0x01
        msg_hash = bytes(msg_hash)
        assert not verify_locally(key, msg_hash, rs)
    elif tamper == "sig":
        rs = bytearray(rs)
        rs[63] ^= 0x01  # flip last bit of S
        rs = bytes(rs)
        assert not verify_locally(key, msg_hash, rs)
    pk = pubkey_xy(key)
    expect_str = "1" if expect else "0"
    print(f'/* Vector {label}: msg={msg!r}, expect={"P" if expect else "F"} */')
    print(emit_array(f"p256_vec_{label}_pubkey", pk))
    print(emit_array(f"p256_vec_{label}_hash", msg_hash))
    print(emit_array(f"p256_vec_{label}_sig", rs))
    print(f"#define P256_VEC_{label.upper()}_EXPECT {expect_str}")
    print('')

print('#endif /* LIB_CRYPTO_FIPS_186_4_P256_H */')
