#!/usr/bin/env python3
"""Generate the q15 sine lookup table for lib/dsp/src/sincos.c.

Emits a full-period sine table of SINCOS_LUT_N int16 entries (Q1.15), used by
dsp_sincos_q15() with linear interpolation between adjacent entries. The table
is production data (checked in), not a test vector — regenerate with:

    python3 lib/dsp/src/gen_sincos_lut.py > lib/dsp/src/sincos_lut.h

With N=1024 the worst-case linear-interpolation error is ~0.15 LSB
((2*pi/N)^2 / 8 * 32768), so the LUT reproduces sin/cos to well under 1 LSB
across the full circle. A checked-in integer table is deterministic on host and
target — unlike runtime libm sinf/cosf, which can differ by a ULP across
toolchains (the same drift the AWGN module warns about).
"""
import math

N = 1024


def q15_round(v: float) -> int:
    s = v * 32768.0
    r = math.floor(s + 0.5) if s >= 0.0 else math.ceil(s - 0.5)
    return max(-32768, min(32767, int(r)))


vals = [q15_round(math.sin(2.0 * math.pi * i / N)) for i in range(N)]

print("/*")
print(" * q15 sine lookup table for lib/dsp/src/sincos.c — generated by")
print(" * lib/dsp/src/gen_sincos_lut.py. Full period, %d entries (Q1.15)." % N)
print(" * Do not edit by hand; regenerate with the script.")
print(" */")
print("#ifndef LIB_DSP_SINCOS_LUT_H")
print("#define LIB_DSP_SINCOS_LUT_H")
print("")
print("#include <stdint.h>")
print("")
print("#define SINCOS_LUT_N %d" % N)
print("")
print("static const int16_t sincos_lut[SINCOS_LUT_N] = {")
for i in range(0, N, 8):
    chunk = ", ".join("%6d" % v for v in vals[i:i + 8])
    print("    %s," % chunk)
print("};")
print("")
print("#endif /* LIB_DSP_SINCOS_LUT_H */")
