#!/usr/bin/env python3
"""Generate golden sin/cos vectors for tests/lib/dsp/test_sincos.c.

Samples the full uint32 phase circle at a set of fixed points and emits the
float64 reference sin/cos quantised to q15. dsp_sincos_q15() (a 1024-entry LUT
with linear interpolation) must match these within a small LSB tolerance — the
same ±2-LSB golden-vector discipline as gen_rrc_vectors.py.

Regenerate with:
    python3 tests/lib/dsp/vectors/gen_sincos_vectors.py > tests/lib/dsp/vectors/sincos_golden.h
"""
import math

# Phase points across the full circle (uint32, 2^32 == 2*pi). Chosen to land
# between LUT entries so the linear interpolation is actually exercised, not
# just the exact table points.
PHASES = [
    0x00000000, 0x08000000, 0x10000000, 0x20000000, 0x30000000,
    0x40000000, 0x55555555, 0x60000000, 0x76543210, 0x80000000,
    0x90000000, 0xAAAAAAAA, 0xC0000000, 0xD0000000, 0xE0000000,
    0xF0000000, 0xFEDCBA98, 0x12345678, 0x3FFFFFFF, 0xBFFFFFFF,
]


def q15_round(v: float) -> int:
    s = v * 32768.0
    r = math.floor(s + 0.5) if s >= 0.0 else math.ceil(s - 0.5)
    return max(-32768, min(32767, int(r)))


two_pi = 2.0 * math.pi

print("/*")
print(" * Golden sin/cos vectors for tests/lib/dsp/test_sincos.c.")
print(" * Generated by tests/lib/dsp/vectors/gen_sincos_vectors.py — float64")
print(" * reference quantised to q15. The LUT (dsp_sincos_q15) must match these")
print(" * within a few LSB across the full uint32 phase circle.")
print(" */")
print("#ifndef LIB_DSP_SINCOS_GOLDEN_H")
print("#define LIB_DSP_SINCOS_GOLDEN_H")
print("")
print("#include <stdint.h>")
print("")
print("typedef struct { uint32_t phase; int16_t sin; int16_t cos; } sincos_vec_t;")
print("")
print("static const sincos_vec_t sincos_golden[] = {")
for p in PHASES:
    theta = (p / 4294967296.0) * two_pi
    s = q15_round(math.sin(theta))
    c = q15_round(math.cos(theta))
    print("    { 0x%08Xu, %6d, %6d }," % (p, s, c))
print("};")
print("")
print("#define SINCOS_GOLDEN_N (sizeof(sincos_golden)/sizeof(sincos_golden[0]))")
print("")
print("#endif /* LIB_DSP_SINCOS_GOLDEN_H */")
