#!/usr/bin/env python3
"""Generate golden RRC tap vectors for tests/lib/dsp/.

Computes a unit-energy root-raised-cosine filter in float64 — the exact
reference the C tap design (lib/dsp/src/rrc.c) must reproduce within +/-2 LSB —
and emits a C header with the quantised q15 taps for the modem's default
configuration (beta=0.35, sps=4, span=8 -> 33 taps).

The closed-form RRC impulse response, its two removable singularities, the
unit-energy normalisation (sum of squares == 1), and the round-half-away-from-
zero quantisation here all mirror rrc.c line for line, so test_rrc.c can assert
the C taps equal these bytes to within a couple of LSB (float64 vs float32
rounding is the only expected source of disagreement).
"""
import math


def rrc_h(t: float, beta: float) -> float:
    """Closed-form RRC impulse response at time t (symbol periods)."""
    if abs(t) < 1e-10:
        return 1.0 - beta + 4.0 * beta / math.pi
    if beta > 0.0 and abs(abs(4.0 * beta * t) - 1.0) < 1e-9:
        a = math.pi / (4.0 * beta)
        return (beta / math.sqrt(2.0)) * (
            (1.0 + 2.0 / math.pi) * math.sin(a)
            + (1.0 - 2.0 / math.pi) * math.cos(a)
        )
    num = math.sin(math.pi * t * (1.0 - beta)) + \
        4.0 * beta * t * math.cos(math.pi * t * (1.0 + beta))
    den = math.pi * t * (1.0 - (4.0 * beta * t) ** 2)
    return num / den


def q15_round(x: float) -> int:
    """Round half away from zero, then saturate to q15."""
    scaled = x * 32768.0
    r = math.floor(scaled + 0.5) if scaled >= 0.0 else math.ceil(scaled - 0.5)
    return max(-32768, min(32767, int(r)))


def design(beta: float, sps: int, span: int) -> list[int]:
    ntaps = sps * span + 1
    centre = (ntaps - 1) / 2.0
    taps = [rrc_h((i - centre) / sps, beta) for i in range(ntaps)]
    energy = sum(v * v for v in taps)
    norm = 1.0 / math.sqrt(energy)
    return [q15_round(v * norm) for v in taps]


BETA, SPS, SPAN = 0.35, 4, 8
taps = design(BETA, SPS, SPAN)

print("/*")
print(" * Golden q15 root-raised-cosine taps for tests/lib/dsp/test_rrc.c.")
print(" *")
print(" * Generated by tests/lib/dsp/vectors/gen_rrc_vectors.py — a float64")
print(" * reference RRC (beta=0.35, sps=4, span=8), unit-energy normalised, and")
print(" * quantised to q15 with round-half-away-from-zero. lib/dsp/src/rrc.c")
print(" * computes the same filter in float32; the host test asserts the C taps")
print(" * match these values within +/-2 LSB.")
print(" */")
print("#ifndef LIB_DSP_RRC_GOLDEN_H")
print("#define LIB_DSP_RRC_GOLDEN_H")
print("")
print("#include <stdint.h>")
print("")
print(f"#define RRC_GOLDEN_BETA  {BETA}f")
print(f"#define RRC_GOLDEN_SPS   {SPS}")
print(f"#define RRC_GOLDEN_SPAN  {SPAN}")
print(f"#define RRC_GOLDEN_NTAPS {len(taps)}")
print("")
print(f"static const int16_t rrc_golden_taps[{len(taps)}] = {{")
for i in range(0, len(taps), 8):
    chunk = ", ".join(f"{v:6d}" for v in taps[i:i + 8])
    print(f"    {chunk},")
print("};")
print("")
print("#endif /* LIB_DSP_RRC_GOLDEN_H */")
