/*
 * Golden q15 root-raised-cosine taps for tests/lib/dsp/test_rrc.c.
 *
 * Generated by tests/lib/dsp/vectors/gen_rrc_vectors.py — a float64
 * reference RRC (beta=0.35, sps=4, span=8), unit-energy normalised, and
 * quantised to q15 with round-half-away-from-zero. lib/dsp/src/rrc.c
 * computes the same filter in float32; the host test asserts the C taps
 * match these values within +/-2 LSB.
 */
#ifndef LIB_DSP_RRC_GOLDEN_H
#define LIB_DSP_RRC_GOLDEN_H

#include <stdint.h>

#define RRC_GOLDEN_BETA  0.35f
#define RRC_GOLDEN_SPS   4
#define RRC_GOLDEN_SPAN  8
#define RRC_GOLDEN_NTAPS 33

static const int16_t rrc_golden_taps[33] = {
        33,    218,    157,   -156,   -417,   -242,    420,   1071,
       936,   -362,  -2215,  -3091,  -1388,   3390,   9959,  15684,
     17954,  15684,   9959,   3390,  -1388,  -3091,  -2215,   -362,
       936,   1071,    420,   -242,   -417,   -156,    157,    218,
        33,
};

#endif /* LIB_DSP_RRC_GOLDEN_H */
