/*
 * Golden sin/cos vectors for tests/lib/dsp/test_sincos.c.
 * Generated by tests/lib/dsp/vectors/gen_sincos_vectors.py — float64
 * reference quantised to q15. The LUT (dsp_sincos_q15) must match these
 * within a few LSB across the full uint32 phase circle.
 */
#ifndef LIB_DSP_SINCOS_GOLDEN_H
#define LIB_DSP_SINCOS_GOLDEN_H

#include <stdint.h>

typedef struct { uint32_t phase; int16_t sin; int16_t cos; } sincos_vec_t;

static const sincos_vec_t sincos_golden[] = {
    { 0x00000000u,      0,  32767 },
    { 0x08000000u,   6393,  32138 },
    { 0x10000000u,  12540,  30274 },
    { 0x20000000u,  23170,  23170 },
    { 0x30000000u,  30274,  12540 },
    { 0x40000000u,  32767,      0 },
    { 0x55555555u,  28378, -16384 },
    { 0x60000000u,  23170, -23170 },
    { 0x76543210u,   7705, -31849 },
    { 0x80000000u,      0, -32768 },
    { 0x90000000u, -12540, -30274 },
    { 0xAAAAAAAAu, -28378, -16384 },
    { 0xC0000000u, -32768,      0 },
    { 0xD0000000u, -30274,  12540 },
    { 0xE0000000u, -23170,  23170 },
    { 0xF0000000u, -12540,  30274 },
    { 0xFEDCBA98u,   -915,  32755 },
    { 0x12345678u,  14159,  29551 },
    { 0x3FFFFFFFu,  32767,      0 },
    { 0xBFFFFFFFu, -32768,      0 },
};

#define SINCOS_GOLDEN_N (sizeof(sincos_golden)/sizeof(sincos_golden[0]))

#endif /* LIB_DSP_SINCOS_GOLDEN_H */
