#!/usr/bin/env python3
"""Generate an ECDSA P-256 keypair for the bootloader.

Emits two artifacts:
  - PKCS#8 unencrypted PEM private key (DO NOT COMMIT — covered by .gitignore).
  - C source file with `const uint8_t bootloader_pubkey[64]` containing the
    raw uncompressed Qx || Qy public key, big-endian, 32 bytes each, no 0x04
    prefix. Matches CRYPTO_ECDSA_P256_PUBKEY_LEN in lib/crypto/inc/crypto.h
    and is consumed directly by crypto_ecdsa_p256_verify().

Usage:
  python3 tools/keygen.py --priv-out <key>.pem --pub-out <pubkey>.c [--seed <bytes>]

If --seed is given, the keypair is derived deterministically from the seed
(useful for reproducible test fixtures). Without --seed the OS RNG is used.

Dependencies: cryptography (`pip install cryptography`).
"""

import argparse
import hashlib
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec

# secp256r1 group order, used to clamp deterministic scalars into [1, n-1].
SECP256R1_N = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551

CURVE = ec.SECP256R1()


def derive_key_from_seed(seed: bytes) -> ec.EllipticCurvePrivateKey:
    """Derive a deterministic P-256 private key from arbitrary seed bytes.

    Same construction as tests/lib/crypto/vectors/gen_vectors.py: SHA-256 the
    seed, reduce mod (n-1), shift to [1, n-1].
    """
    digest = hashlib.sha256(seed).digest()
    scalar = int.from_bytes(digest, "big") % (SECP256R1_N - 1) + 1
    return ec.derive_private_key(scalar, CURVE)


def pubkey_xy(key: ec.EllipticCurvePrivateKey) -> bytes:
    """Return the 64-byte raw uncompressed Qx || Qy public key."""
    nums = key.public_key().public_numbers()
    return nums.x.to_bytes(32, "big") + nums.y.to_bytes(32, "big")


def emit_pubkey_c(pubkey_bytes: bytes, source_note: str) -> str:
    """Render a C source file containing the public key as a uint8_t array.

    `source_note` documents the provenance (random or seed) at the top.
    """
    if len(pubkey_bytes) != 64:
        raise ValueError(f"pubkey must be 64 bytes, got {len(pubkey_bytes)}")
    fingerprint = hashlib.sha256(pubkey_bytes).hexdigest()

    lines = [
        "/*",
        " * Bootloader ECDSA-P256 public key.",
        " *",
        " * Generated by tools/keygen.py. Do not edit by hand.",
        f" * Source:      {source_note}",
        f" * Fingerprint: SHA-256 = {fingerprint}",
        " *",
        " * Format: uncompressed Qx || Qy, big-endian, 32 bytes each, no 0x04",
        " * prefix. Matches CRYPTO_ECDSA_P256_PUBKEY_LEN in",
        " * lib/crypto/inc/crypto.h.",
        " */",
        "",
        "#include <stdint.h>",
        "",
        "const uint8_t bootloader_pubkey[64] = {",
    ]
    for i in range(0, 64, 8):
        chunk = ", ".join(f"0x{b:02x}" for b in pubkey_bytes[i : i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate an ECDSA-P256 keypair for the bootloader."
    )
    parser.add_argument(
        "--priv-out",
        required=True,
        type=Path,
        help="Path to write the PKCS#8 PEM private key (gitignored by convention).",
    )
    parser.add_argument(
        "--pub-out",
        type=Path,
        default=Path("apps/bootloader/loader/bootloader_pubkey.c"),
        help=(
            "Path to write the public key C source. Default targets the future "
            "Phase 1.5 bootloader location."
        ),
    )
    parser.add_argument(
        "--seed",
        type=str,
        default=None,
        help=(
            "Optional UTF-8 string seed for deterministic key derivation "
            "(test fixtures only — do NOT use for production keys)."
        ),
    )
    args = parser.parse_args(argv)

    if args.seed is not None:
        key = derive_key_from_seed(args.seed.encode("utf-8"))
        source_note = f'derived from seed "{args.seed}" (deterministic)'
    else:
        key = ec.generate_private_key(CURVE)
        source_note = "OS RNG (cryptography.ec.generate_private_key)"

    priv_pem = key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )

    args.priv_out.parent.mkdir(parents=True, exist_ok=True)
    args.priv_out.write_bytes(priv_pem)
    # PEM contains a private key; restrict perms.
    args.priv_out.chmod(0o600)

    pub_bytes = pubkey_xy(key)
    args.pub_out.parent.mkdir(parents=True, exist_ok=True)
    args.pub_out.write_text(emit_pubkey_c(pub_bytes, source_note))

    print(f"wrote private key -> {args.priv_out}")
    print(f"wrote public key  -> {args.pub_out}")
    print(f"pubkey fingerprint: {hashlib.sha256(pub_bytes).hexdigest()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
